### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by nicost** [micro-manager/LightSheetManager#100]
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /C:/projects/Altos/LightSheetManager/src/main/java/org/micromanager/lightsheetmanager/model/AcquisitionEngine.java:[247,39] constructor AcqEngJMDADataSink in class org.micromanager.acquisition.internal.acqengjcompat.AcqEngJMDADataSink cannot be applied to given types;
  required: org.micromanager.events.EventManager
  found: org.micromanager.events.EventManager,org.micromanager.acquisition.internal.acqengjcompat.AcqEngJAdapter
  reason: actual and formal argument lists differ in length
[ERROR] /C:/projects/Altos/LightSheetManager/src/main/java/org/micromanager/lightsheetmanager/model/AcquisitionEngine.java:[1045,34] constructor AcqEngJMDADataSink in class org.micromanager.acquisition.internal.acqengjcompat.AcqEngJMDADataSink cannot be applied to given types;
  required: org.micromanager.events.EventManager
  found: org.micromanager.events.EventManager,org.micromanager.acquisition.internal.acqengjcompat.AcqEngJAdapter
  reason: actual and formal argument lists differ in length
[INFO] 2 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.116 s
[INFO] Finished at: 2023-09-05T10:18:22-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project LightSheetManager: Compilation failure: Compilation failure:
[ERROR] /C:/projects/Altos/LightSheetManager/src/main/java/org/micromanager/lightsheetmanager/model/AcquisitionEngine.java:[247,39] constructor AcqEngJMDADataSink in class org.micromanager.acquisition.internal.acqengjcompat.AcqEngJMDADataSink cannot be applied to given types;
[ERROR]   required: org.micromanager.events.EventManager
[ERROR]   found: org.micromanager.events.EventManager,org.micromanager.acquisition.internal.acqengjcompat.AcqEngJAdapter
[ERROR]   reason: actual and formal argument lists differ in length
[ERROR] /C:/projects/Altos/LightSheetManager/src/main/java/org/micromanager/lightsheetmanager/model/AcquisitionEngine.java:[1045,34] constructor AcqEngJMDADataSink in class org.micromanager.acquisition.internal.acqengjcompat.AcqEngJMDADataSink cannot be applied to given types;
[ERROR]   required: org.micromanager.events.EventManager
[ERROR]   found: org.micromanager.events.EventManager,org.micromanager.acquisition.internal.acqengjcompat.AcqEngJAdapter
[ERROR]   reason: actual and formal argument lists differ in length
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
(base)

**Comment by bls337** [comment]
I got that error too. I fixed it by copying the latest MMJ_.jar to LightSheetManager/lib/MMJ_.jar, does this work for you?
