### ISSUE TITLE
Bug on startup with demo config

### ISSUE THREAD

**Issue by nicost** [micro-manager/LightSheetManager#165]
Created a Config starting with the MM Demo config, added LightSheeetManager device (only change from default was to set SCAPE).  Starting LightSheetManager shows a dialog with the content ")", and the following in the logs:

----------------
loaded json: {"timingSettings_":{"scansPerSlice_":1,"delayBeforeScan_":0.0,"scanDuration_":10.0,"delayBeforeLaser_":1.0,"laserTriggerDuration_":1.0,"delayBeforeCamera_":0.0,"cameraTriggerDuration_":1.0,"cameraExposure_":1.0,"sliceDuration_":0.0,"alternateScanDirection_":false},"volumeSettings_":{"firstView_":0,"numViews_":1,"slicesPerView_":0,"delayBeforeView_":0.0,"sliceStepSize_":0.0,"startPosition_":0.0,"centerPosition_":0.0,"endPosition_":0.0},"sliceSettingsLS_":{"scanResetTime_":3.0,"scanSettleTime_":1.0,"shutterWidth_":5.0,"shutterSpeedFactor_":1.0},"sliceSettings_":{"slicePeriod_":10.0,"sampleExposure_":1.0,"minimizeSlicePeriod_":false},"scanSettings_":{"scanAccelerationFactor_":1.0,"scanOvershootDistance_":0,"scanRetraceSpeed_":67.0,"scanAngleFirstView_":45.0,"scanReturnToOriginalPosition_":false,"scanFromCurrentPosition_":false,"scanFromNegativeDirection_":false},"sheetCalibration_":{"sheetWidth_":0.0,"sheetOffset_":0.0,"useAutoSheetWidth_":false,"autoSheetWidthPerPixel_":0.0,"scanSpeed_":0.0,"scanOffset_":0.0,"liveScanPeriod_":20.0},"sliceCalibration_":{"sliceSlope_":0.0,"sliceOffset_":0.0},"sliceCalibration2_":{"sliceSlope_":0.0,"sliceOffset_":0.0},"acquisitionMode_":"NONE","channelMode_":"VOLUME_HW","cameraMode_":"INTERNAL","useChannels_":false,"useTimePoints_":false,"useAutofocus_":false,"useMultiplePositions_":false,"useHardwareTimePoints_":false,"useStageScanning_":false,"useAdvancedTiming_":false,"numTimePoints_":0,"timePointInterval_":0,"postMoveDelay_":0,"numChannels_":0,"channelGroup_":"","channels_":[],"saveNamePrefix_":"","saveDirectory_":"","saveDuringAcq_":false,"demoMode_":false,"saveMode_":"NDTIFF","autofocusSettings_":{"numImages_":4,"stepSize_":1.0,"mode_":"FIXED_PIEZO_SWEEP_SLICE","scoring_":"VOLATH","fit_":"GAUSSIAN","r2_":1.0,"timePointInterval_":1,"useEveryStagePass_":false,"useBeforeAcquisition_":false,"channel_":"","maxOffset_":1.0,"autoUpdateOffset_":true,"autoUpdateMaxOffset_":5.0}}
img props: 1
ill props: 1
2023-10-03T10:55:01.789160 tid3328 [IFO,App] UserSettings: Added key "sheetCalibrations_" to the loaded settings.
2023-10-03T10:55:01.789180 tid3328 [IFO,App] UserSettings: Added key "liveScanPeriod_" to the loaded settings.
2023-10-03T10:55:01.789188 tid3328 [IFO,App] UserSettings: Added key "sliceCalibrations_" to the loaded settings.
2023-10-03T10:55:02.777329 tid3328 [IFO,App] 
                                   [       ] java.lang.ArrayIndexOutOfBoundsException: 0 in Thread[AWT-EventQueue-0,6,main]
                                   [       ]   at org.micromanager.lightsheetmanager.gui.tabs.channels.ChannelTable.<init>(ChannelTable.java:45)
                                   [       ]   at org.micromanager.lightsheetmanager.gui.tabs.channels.ChannelTablePanel.createUserInterface(ChannelTablePanel.java:43)
                                   [       ]   at org.micromanager.lightsheetmanager.gui.tabs.channels.ChannelTablePanel.<init>(ChannelTablePanel.java:35)
                                   [       ]   at org.micromanager.lightsheetmanager.gui.tabs.AcquisitionTab.createUserInterface(AcquisitionTab.java:152)
                                   [       ]   at org.micromanager.lightsheetmanager.gui.tabs.AcquisitionTab.<init>(AcquisitionTab.java:78)
                                   [       ]   at org.micromanager.lightsheetmanager.gui.tabs.TabPanel.createUserInterface(TabPanel.java:65)
                                   [       ]   at org.micromanager.lightsheetmanager.gui.tabs.TabPanel.<init>(TabPanel.java:56)
                                   [       ]   at org.micromanager.lightsheetmanager.gui.LightSheetManagerFrame.createUserInterface(LightSheetManagerFrame.java:115)
                                   [       ]   at org.micromanager.lightsheetmanager.gui.LightSheetManagerFrame.<init>(LightSheetManagerFrame.java:54)
                                   [       ]   at org.micromanager.lightsheetmanager.LightSheetManagerPlugin.onPluginSelected(LightSheetManagerPlugin.java:44)
                                   [       ]   at org.micromanager.internal.pluginmanagement.DefaultPluginManager.lambda$addSubMenuItem$0(DefaultPluginManager.java:182)

**Comment by bls337** [comment]
This should be fixed now, feel free to try again, there will likely be some other error because there are too many references to ASI hardware in the gui at the moment, but you can open another issue or post it here and I can work my way through them.
