### ISSUE TITLE
Datastore

### ISSUE THREAD

**Issue by henrypinkard** [micro-manager/LightSheetManager#23]
@bls337 I see there are options on the GUI for Single Plane Tiff and OME Tiff (though no NDTiff as of yet). However, I don't see any option in AcquisitionSettings for determining which is selected

**Comment by bls337** [comment]
I just implemented this feature, in [#25](https://github.com/micro-manager/LightSheetManager/pull/25). AcquisitionSettings has a base builder, which is where the save settings are.
